name: gtk macOS

# Dependencies of Glib package
env:
  MACOS_BREW: ${{ 'glib gobject-introspection pango atk gtk+3 cairo glib-networking gdk-pixbuf jq' }}


on:
  push:
    branches:
      - swift52
  pull_request:
    branches:
      - swift52
jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          ref: swift52
          path: gir2swift

      - name: Checkout testing repo
        uses: actions/checkout@v2
        with:
          repository: rhx/SwiftGtk
          ref: swift52
          path: SwiftGtk

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build gtk
        run: |
          cd SwiftGtk
          swift package update
          ../gir2swift/gir2swift-generation-driver.sh generate "$PWD" "$GIR2SWIFT_PATH"
          swift build -Xswiftc -suppress-warnings `../gir2swift/gir2swift-generation-driver.sh "c-flags" "${PWD}"`
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ../SwiftGtk
          swift package clean
          rm -rf .build/repositories
          cd ..
