name: macOS 10.15

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'libxml2 gobject-introspection' }}

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  # macOS tasks
  build-mac-catalina-swift-latest:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Test gir2swift
        run: |
          cd gir2swift
          ./test.sh
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            gir2swift/
          retention-days: 1
