name: gtk Ubuntu

# Dependencies of Glib package
env:
  UBUNTU_APT: ${{ 'libpango1.0-dev libglib2.0-dev libgdk-pixbuf2.0-dev gobject-introspection libcairo2-dev libatk1.0-dev glib-networking libgtk-3-dev libgirepository1.0-dev jq' }}
  

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
jobs:
  # Ubuntu tasks
  build-ubuntu-swift-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Checkout testing repo
        uses: actions/checkout@v2
        with:
          repository: rhx/SwiftGtk
          ref: development
          path: SwiftGtk

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build gtk
        run: |
          cd SwiftGtk
          swift package update
          ../gir2swift/gir2swift-generation-driver.sh generate "$PWD" "$GIR2SWIFT_PATH"
          swift build -Xswiftc -suppress-warnings
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ../SwiftGtk
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-ubuntu
          path: |
            gir2swift/
            SwiftGtk/Sources/
          retention-days: 1
